-- HAVING 절: 학생의 총 challenge 개수가 유일하거나 최대인 경우만 출력
SELECT H.HACKER_ID, H.NAME, COUNT(*) AS CHALLENGES_CREATED
FROM Hackers H
JOIN Challenges C ON H.HACKER_ID=C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CHALLENGES_CREATED IN ( SELECT SUB2.CHALLENGES_CREATED 
                               FROM ( SELECT HACKER_ID, COUNT(*) AS CHALLENGES_CREATED FROM Challenges GROUP BY HACKER_ID ) SUB2 
                               GROUP BY SUB2.CHALLENGES_CREATED 
                               HAVING COUNT(*)=1
                             )
OR CHALLENGES_CREATED = ( SELECT MAX(SUB1.CHALLENGES_CREATED)
                          FROM ( SELECT COUNT(*) AS CHALLENGES_CREATED  FROM Challenges GROUP BY HACKER_ID) SUB1)
ORDER BY CHALLENGES_CREATED DESC, H.HACKER_ID;
