SELECT S2.HACKER_ID, H.NAME, S2.TOTAL_SCORE
FROM
(
   SELECT S1.HACKER_ID, SUM(MAX_SCORE) AS TOTAL_SCORE
   FROM ( 
         SELECT HACKER_ID, MAX(SCORE) AS MAX_SCORE 
         FROM SUBMISSIONS 
         GROUP BY HACKER_ID, CHALLENGE_ID
   ) S1
   GROUP BY S1.HACKER_ID
   HAVING TOTAL_SCORE != 0
) S2
JOIN HACKERS H ON H.HACKER_ID=S2.HACKER_ID
ORDER BY S2.TOTAL_SCORE DESC, S2.HACKER_ID
;
