SELECT W.ID, WP.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W
JOIN WANDS_PROPERTY WP ON W.CODE=WP.CODE AND WP.IS_EVIL=0
WHERE W.COINS_NEEDED=( SELECT MIN(W1.COINS_NEEDED) 
                       FROM WANDS W1 
                       JOIN WANDS_PROPERTY W2 ON W1.CODE=W2.CODE 
                       WHERE W2.IS_EVIL=0 AND W1.POWER=W.POWER AND W2.AGE=WP.AGE
                     )
ORDER BY W.POWER DESC, WP.AGE DESC;
