-- FROM 절의 서브쿼리에 의해 내 급여를 조회할 수 있음
-- P2는 친구의 급여를 알기 위한 테이블 JOIN
SELECT S.NAME
FROM
(SELECT S.ID, S.NAME, F.FRIEND_ID, P1.SALARY AS MY_SALARY FROM STUDENTS S
JOIN FRIENDS F ON F.ID=S.ID
JOIN PACKAGES P1 ON P1.ID=F.ID) S
JOIN PACKAGES P2 ON S.FRIEND_ID=P2.ID
WHERE S.MY_SALARY < P2.SALARY
ORDER BY P2.SALARY;
